name: CI

on:
  push:
    paths:
      - 'news-tracker-main/**'
  pull_request:
    paths:
      - 'news-tracker-main/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.9.0'

      - name: Install dependencies
        run: |
          cd news-tracker-main
          npm i

      - name: Run tests
        run: |
          npm test
