name: CI

on:
  push:
    paths:
      - 'news-tracker-main/**'
      - 'hits-hackathon/.github/workflows/front_ci.yml'
  pull_request:
    paths:
      - 'news-tracker-main/**'
      - 'hits-hackathon/.github/workflows/front_ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.9.0'

      - name: Install dependencies
        run: |
          cd news-tracker-main
          npm i

      - name: Run tests
        run: |
          cd news-tracker-main
          npm test
